import NextAuthSessionProvider from "@/providers/sessionProvider"
import type { Metadata } from "next"
import "./globals.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-800 text-white">
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>    
      </body>
    </html>
  )
}
